import 'dart:io';

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/models/saved_document_model.dart';
import '../../../core/models/scanned_page_draft.dart';
import '../../../core/providers/documents_provider.dart';
import '../../../core/theme/app_spacing.dart';
import '../../../core/theme/app_typography.dart';
import '../../../shared/widgets/buttons/primary_button.dart';
import '../../../shared/widgets/buttons/secondary_button.dart';
import '../../../shared/widgets/dialogs/confirmation_dialog.dart';
import '../../../shared/widgets/dialogs/success_dialog.dart';
import '../../../shared/widgets/text_fields/app_dropdown.dart';
import '../../../shared/widgets/text_fields/app_text_field.dart';
import '../application/scan_processing_service.dart';
import '../application/scanner_session_controller.dart';

/// Last step before saving: name, category, and optional notes for the
/// scanned document. Saving copies the chosen page's processed image (plus
/// a generated thumbnail) into permanent local storage via
/// [DocumentsProvider.saveScannedDocument] and adds it to My Documents.
class ScannerDetailsScreen extends StatefulWidget {
  final ScannerSessionController controller;

  /// Looks up the already-generated (cached) processed preview file for a
  /// page's currently-selected mode — computed by [ScannerPreviewScreen],
  /// which owns the processing cache, rather than this screen
  /// re-processing the image itself.
  final String? Function(ScannedPageDraft page) processedImagePathFor;

  const ScannerDetailsScreen({
    super.key,
    required this.controller,
    required this.processedImagePathFor,
  });

  @override
  State<ScannerDetailsScreen> createState() => _ScannerDetailsScreenState();
}

class _ScannerDetailsScreenState extends State<ScannerDetailsScreen> {
  late final TextEditingController _nameController;
  final TextEditingController _notesController = TextEditingController();
  final ScanProcessingService _processingService = ScanProcessingService();
  SavedDocumentCategory _category = SavedDocumentCategory.uncategorized;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    final today = DateFormat('MMM d, yyyy').format(DateTime.now());
    _nameController = TextEditingController(text: 'Scanned Document $today');
  }

  @override
  void dispose() {
    _nameController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _showMessage(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  Future<bool> _confirmDiscard() {
    return ConfirmationDialog.show(
      context,
      title: 'Discard Scan?',
      message: 'Your captured document has not been saved.',
      confirmLabel: 'Discard',
      cancelLabel: 'Continue Editing',
      isDestructive: true,
    );
  }

  Future<void> _handleCancel() async {
    final discard = await _confirmDiscard();
    if (discard && mounted) Navigator.of(context).pop();
  }

  Future<void> _handleSave() async {
    if (_nameController.text.trim().isEmpty) {
      _showMessage('Enter a document name.');
      return;
    }

    final pages = widget.controller.pages
        .where((page) => page.imagePath != null)
        .toList();
    if (pages.isEmpty) {
      _showMessage('No captured page to save.');
      return;
    }

    final documentsProvider = context.read<DocumentsProvider>();
    setState(() => _isSaving = true);

    String? thumbnailPath;
    // Files generated by this method itself (as opposed to looked up from
    // [ScannerPreviewScreen]'s cache, which owns and cleans up its own
    // entries) — cleaned up here once they've been copied into permanent
    // storage.
    final ownTempFiles = <String>[];
    try {
      final orderedProcessedPaths = <String>[];
      for (final page in pages) {
        final cached = widget.processedImagePathFor(page);
        if (cached != null) {
          orderedProcessedPaths.add(cached);
          continue;
        }
        // A page that was never opened in the preview tab strip has no
        // cached preview yet — process it now rather than skip it, so
        // every captured page still makes it into the saved document.
        try {
          final generated = await _processingService.processForMode(
            sourcePath: page.imagePath!,
            mode: page.selectedMode,
          );
          orderedProcessedPaths.add(generated);
          ownTempFiles.add(generated);
        } on ScanProcessingException {
          if (mounted) {
            setState(() => _isSaving = false);
            _showMessage('One of the pages could not be processed.');
          }
          return;
        }
      }

      final String fileToSavePath;
      if (orderedProcessedPaths.length == 1) {
        fileToSavePath = orderedProcessedPaths.first;
      } else {
        fileToSavePath = await _processingService.combinePagesToPdf(
          orderedProcessedPaths,
        );
        ownTempFiles.add(fileToSavePath);
      }

      thumbnailPath = await _processingService.generateThumbnail(
        orderedProcessedPaths.first,
      );

      final result = await documentsProvider.saveScannedDocument(
        processedFile: File(fileToSavePath),
        displayName: _nameController.text.trim(),
        category: _category,
        notes: _notesController.text.trim(),
        scanMode: pages.first.selectedMode,
        pageCount: orderedProcessedPaths.length,
        thumbnailFile: File(thumbnailPath),
      );

      if (!mounted) return;
      switch (result.outcome) {
        case ScannedDocumentSaveOutcome.tooLarge:
          setState(() => _isSaving = false);
          _showMessage('File is too large to save.');
          return;
        case ScannedDocumentSaveOutcome.error:
          setState(() => _isSaving = false);
          _showMessage('Saving failed. Please try again.');
          return;
        case ScannedDocumentSaveOutcome.success:
          break;
      }
    } catch (_) {
      if (mounted) {
        setState(() => _isSaving = false);
        _showMessage('Saving failed. Please try again.');
      }
      return;
    } finally {
      // Every file saved into My Documents is a copy (DocumentStorageService
      // never moves/adopts the source), so anything generated just for this
      // save is safe to delete once it's been handed off, success or not.
      await _processingService.deleteIfExists(thumbnailPath);
      for (final path in ownTempFiles) {
        await _processingService.deleteIfExists(path);
      }
    }

    if (!mounted) return;
    setState(() => _isSaving = false);
    await SuccessDialog.show(context, message: 'Document scanned successfully.');
    if (!mounted) return;
    context.go('/profile/documents');
  }

  @override
  Widget build(BuildContext context) {
    final pageCount = widget.controller.pageCount;
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) async {
        if (didPop) return;
        final discard = await _confirmDiscard();
        if (discard && context.mounted) Navigator.of(context).pop();
      },
      child: Scaffold(
        appBar: AppBar(title: const Text('Document Details')),
        body: SafeArea(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(
              AppConstants.screenPaddingHorizontal,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                if (pageCount > 1) ...[
                  Container(
                    padding: const EdgeInsets.all(AppSpacing.md),
                    decoration: BoxDecoration(
                      color: AppColors.statusInfoBg,
                      borderRadius: BorderRadius.circular(
                        AppConstants.borderRadiusMedium,
                      ),
                    ),
                    child: Row(
                      children: [
                        const Icon(
                          Icons.info_outline,
                          color: AppColors.statusInfo,
                          size: 20,
                        ),
                        const SizedBox(width: AppSpacing.sm),
                        Expanded(
                          child: Text(
                            'These $pageCount pages will be combined into '
                            'a single PDF document.',
                            style: AppTypography.caption.copyWith(
                              color: AppColors.statusInfo,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: AppSpacing.lg),
                ],
                AppTextField(
                  controller: _nameController,
                  label: 'Document Name',
                  textCapitalization: TextCapitalization.sentences,
                ),
                const SizedBox(height: AppSpacing.lg),
                AppDropdown<SavedDocumentCategory>(
                  value: _category,
                  label: 'Document Category',
                  items: [
                    for (final category in SavedDocumentCategory.values)
                      DropdownMenuItem(
                        value: category,
                        child: Text(category.label),
                      ),
                  ],
                  onChanged: (value) {
                    if (value != null) setState(() => _category = value);
                  },
                ),
                const SizedBox(height: AppSpacing.lg),
                AppTextField(
                  controller: _notesController,
                  label: 'Notes (optional)',
                  hint: 'Add any additional details about this document',
                  maxLines: 4,
                  textCapitalization: TextCapitalization.sentences,
                ),
                const SizedBox(height: AppSpacing.xl),
                Row(
                  children: [
                    Expanded(
                      child: SecondaryButton(
                        label: 'Cancel',
                        onPressed: _isSaving ? null : _handleCancel,
                      ),
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      flex: 2,
                      child: PrimaryButton(
                        label: 'Save to My Documents',
                        isLoading: _isSaving,
                        onPressed: _isSaving ? null : _handleSave,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
